// @ts-expect-error — virtual module generated by nuxt-opensearch module setup
import { config } from '#nuxt-opensearch/config.mjs'
import type { ModuleOptions } from '../../../module'

export default defineEventHandler((event) => {
  setHeader(event, 'Content-Type', 'application/opensearchdescription+xml')
  return generateOpenSearchXML(config as ModuleOptions)
})

function generateOpenSearchXML(options: ModuleOptions): string {
  const {
    name = 'Search',
    searchUrl = '/search?q={searchTerms}',
    description = 'Search this site',
    icon,
    contact,
    language,
    outputEncoding = 'UTF-8',
    inputEncoding = 'UTF-8',
  } = options

  const lines = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">',
    `  <ShortName>${escapeXml(name)}</ShortName>`,
    `  <Description>${escapeXml(description)}</Description>`,
    `  <Url type="text/html" template="${escapeXml(searchUrl)}" />`,
  ]

  if (outputEncoding) lines.push(`  <OutputEncoding>${escapeXml(outputEncoding)}</OutputEncoding>`)
  if (inputEncoding) lines.push(`  <InputEncoding>${escapeXml(inputEncoding)}</InputEncoding>`)
  if (icon) lines.push(`  <Image>${escapeXml(icon)}</Image>`)
  if (language) lines.push(`  <Language>${escapeXml(language)}</Language>`)
  if (contact) lines.push(`  <Contact>${escapeXml(contact)}</Contact>`)

  lines.push('</OpenSearchDescription>')
  return lines.join('\n')
}

function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}
